### PR TITLE
Ignore suggestions based on previously ignored

### LINKED ISSUE #37: Suggestions table gets out of control
1) After less than 1 month in production, `Suggestions` table has grown to 500 000 records.
2) There should be a way to exclude certain URLs from suggestions, such as health probes (`/episerver/health` or similar).

### PR DESCRIPTION
**Pull request by ellinge**
Fixes #37 

Now suggestions are not added if a matching ignore is found.

Also rewrote the buffering of 404 to allow logging if threshold has passed as well. Meaning the buffer can be less than buffersize before being processed. Seems logical to me but perhaps there's a reason for waiting to fill the buffersize always.

### CODE REVIEW

**Comment by ellinge** [comment]
@marisks shouln't LogQueue.Count be used instead of bufferSize in check of threshold as well?

**Comment by marisks** [comment]
We are working on rewriting the whole logging logic for Suggestions. This PR will be out of date soon.

**Comment by ellinge** [comment]
How far away? It would be nice to avoid getting a lot of suggestions already ignored.

**Comment by jevgenijsp** [comment]
Closing this issue, due to the fix was provided here: https://github.com/Geta/geta-notfoundhandler/pull/134

**Pull request closed without merging**
